Repository JumpersDev1/KS14, pull requests merged in 2025-06, with the labels that each got.

#29 fix teslagate,speczone and spacelaw test fails
  Content.Server/DeviceLinking/Systems/AutoLinkSystem.cs
  Content.Server/_KS14/specZones/EntitySystems/SpecSignalPropagatorSystem.cs
  Resources/Prototypes/Recipes/Lathes/electronics.yml
  Resources/Prototypes/_Goobstation/Recipes/Lathes/Packs/circuits.yml
  Resources/Prototypes/_KS14/Entities/Structures/Machines/teslagate.yml
  Resources/Prototypes/_KS14/Recipes/Lathe/teslagate.yml
  Resources/migration.yml
Labels: size/S

#38 And831 ert loadout change
  Resources/Locale/en-US/_KS14/set-selector/selectable-sets.ftl
  Resources/Prototypes/Roles/Jobs/CentComm/emergencyresponseteam.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Specific/CentralCommand/set_selectors.yml
  Resources/Prototypes/_KS14/Catalog/selectable_sets.yml
Labels: Enhancement, size/M, Balance, Adjustment

#45 Futurechronoupgrades
  Resources/Prototypes/Entities/Clothing/Eyes/hud.yml
  Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Prototypes/_Goobstation/Entities/Clothing/Back/specific.yml
  Resources/Prototypes/_Goobstation/Entities/Clothing/Hands/gloves.yml
  Resources/Prototypes/_Goobstation/Entities/Clothing/Masks/masks.yml
  Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/_Goobstation/Entities/Clothing/Shoes/boots.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Tools/tools.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Melee/stasisbaton.yml
  Resources/Prototypes/_Goobstation/Reagents/medicine.yml
  Resources/Prototypes/_Goobstation/Roles/GhostRoles/Fun/chrono_legionnaire.yml
  Resources/Prototypes/_KS14/Entities/Clothing/Eyes/future.yml
  Resources/Prototypes/_KS14/Entities/Clothing/Hands/future.yml
Labels: size/M, Balance, Adjustment

#34 Fix anomaly infections immobilizing you
  Content.Shared/Anomaly/SharedAnomalySystem.cs
Labels: size/XS, Fix, Port
